### ISSUE TITLE
Spanish Localization: review and update

### ISSUE THREAD

**Issue by cyz** [education/codespaces-teaching-template-py#39]
Hi all 👋

We need review the existing Spanish translation and make sure it is working according to the English content.

Main folder: [https://github.com/education/codespaces-teaching-template-py](https://github.com/education/codespaces-teaching-template-py)

**Please compare each file below to its original in English and if required, please send a PR.**
| File | Status         |
|------|----------------|
| README.md     | pending review |
| example-notebook.ipynb      | pending review |
| slides_es.pptx    | pending review |

The localized files should be in the **`translations/es`** folder. 

🚀After your review, if you find that there is no need to submit a pull request with file changes, please comment on this issue with the status **DONE** for each file.

**Comment by OscarSantosMu** [comment]
@cyz I will translate the content to Spanish

**Comment by OscarSantosMu** [comment]
Hey @cyz , I sent the [PR](https://github.com/education/codespaces-teaching-template-py/pull/41). Let me know if changes are fine.

**Comment by cyz** [comment]
PR #41  approved, congratulations @OscarSantosMu on your first GitHub contribution!
![image](https://github.com/education/codespaces-teaching-template-py/assets/2198735/8ece31ae-64e0-4e2c-aab6-24b54f31f968)
